### ISSUE TITLE
Redundant char "*" found at README file.

### ISSUE THREAD

**Issue by lesschar** [idanarye/vim-yankitute#2]
At this paragraph in README:

Finally, we need to send an email to our team with that list of fields. Again, we mark the entire table creation command in visual mode, but this time we use: '<,'>Yankitute*/\v\,\s*(\w+)/\1. This will put in the clipboard:

 '<,'>Yankitut*/\v\,\s_(\w+)/\1 ==>  '<,'>Yankitute/\v\,\s_(\w+)/\1.

 A redundant char "*" found.

**Comment by idanarye** [comment]
The `*` is not redundant - without it the pattern will be copied to the default internal Vim register. `*` is needed so it'll be copied to the clipboard(register `*`)

**Comment by lesschar** [comment]
When `*` added, i get an error as follow:

E486: Pattern not found: /\v\,\s

**Comment by idanarye** [comment]
I see...

It's not an error in the documentation - it's an actual bug. It seems like `*` was not being passed as the register, and thus becomes the first character of the actual argument and therefore the delimiter(which is why it thinks the pattern is `/\v\,\s`(what's inside the "`*`"s) instead of `\v\,\s*(\w+)`(what's inside the "`/`"s).

**Comment by lesschar** [comment]
So is the right way to fix it by only add `*` to this line in autoload\yankitute.vim as follow:

```
    let [l:reg, l:cmd] = a:reg =~? '[a-z0-9*"]' ? [a:reg, a:cmd] : ['"', a:reg . a:cmd]
```

Uh, I am not familiar with vimscript.

**Comment by idanarye** [comment]
This whole checks seems a bit redundant to me...

@PeterRincker - do you remember why you've added that check? My original code was simply trusting Vim to decide if the user specified a register or not - did you find that it didn't work properly or something?

**Comment by PeterRincker** [comment]
@idanarye If i remember correctly the check was there to help distinguish the register from the delimiter other than `/`. There is no reason I can think of that the register cannot be `+`/`*`.

To see the changes take a look at my most recent [commit](https://github.com/PeterRincker/vim-yankitute/commit/ac10f020b35cc37830e2449f784fb0bc314e3111).

**Comment by idanarye** [comment]
That's still not accounting for all registers... 
- `A` - `Z` - the _appending_ version of the letters registers
- `-` - The small delete register. Not sure if anyone will ever need it, but I see no reason not to support it

The registers we won't support are:
- The read-only registers, for obvious reasons
- The alternate buffer register `#`. It's writable, but only so plugins can restore it after changing it - I don't think we should support it

**Comment by lesschar** [comment]
Thanks idanarye, I learn a lot from your explain above and the vim manual.
